<?php

include('security.php');
include('includes/header.php');
include('includes/navbar.php');
?>

<div class='clearfix' style="overflow: scroll;height: 600px;overflow-x:hidden; ">
<div class='col-md-12' style="margin-left:50px;margin-top:50px;">
<h1 class='gust-margin--large--bottom gust-margin--large--top'>
Terms of Service
</h1>
</div >
<div class="overflow-auto">
<div class='col-md-10' style="margin-left:50px;" align="justify">
<p><b>TERMS OF SERVICE</b></p>
<p>Thank you for your interest in Gust. Please review the following Terms of Service, which will govern your registration with and use of the Gust Platform. </p>
<p>By using the Gust Platform, you agree to the terms and conditions ('Terms of Service') contained in this document ('Agreement') as well as to the terms of the Gust Privacy Policy, which is available at http://www.gust.com/privacy-policy You agree to accept these Terms of Service electronically. If you do not want to be bound by the Terms of Service, you may not make use of the Gust Platform. </p>
<h3><b>DEFINITIONS</b></h3>
<p>“Accredited Investor” for Users in the United States shall have the meaning set forth under United States Securities laws, as discussed in the section entitled “Accredited Investors” below, and for Users outside of the United States shall have the equivalent meaning, if any, as set forth in the applicable securities laws in such User’s jurisdiction of residence.</p>
<p>“Content” means all information and content available on the Gust Platform (if uploaded by Gust, “Gust Content”, and if uploaded by a User, “User Content”) and its “look and feel”, except all User submissions, including but not limited to trademarks, logos, service marks, copyrighted works, text, graphics, logos, button icons, images, audio/video clips, data compilations and software, and the compilation and organization thereof.</p>
<p>“Gust” means Gust, Inc, a Delaware limited liability company, 44 West 28th Street, New York, NY 10001 USA and owner of the Gust Platform. </p>
<p>“Services” refers to all products and services provided to you by Gust </p>
<p>“Organization” means an investor group (organized group of investors) as well as business plan competitions, economic development agencies, entrepreneur conferences, financial institutions, incubators/accelerators, non-profits, accounting firms (service provider), advisors (service provider), family offices (service provider), law firms (service provider), universities, and venture funds</p>
<p>“Registered User” shall mean any user or person who interacts with the Gust Content or User Content via the Gust Platform.</p>
<h3><b>Description of the Gust Platform</b></h3>
<p>Gust provides resources and tools to entrepreneurs, Organizations and Accredited Investors. We have built the Gust Platform to meet the needs of the entrepreneur, VC, investor, and angel community. The Gust Platform refers to the tools and services offered to Registered Users of Gust, including its wholly-owned subsidiaries and affiliates. This includes any and all of the Content thereon and services provided by Gust on or in conjunction with websites wholly owned by Gust, including but not limited to, application program interfaces (“api’s”), storage, email, professional services, and collaboration services. Such tools and services include, but are not limited to, the offerings on the following websites: </p>
<p>Gust (gust.com): A web application that primarily provides deal flow management, deal collaboration, and other tools and services for entrepreneurs, companies, investors and organizations.</p>
<p>Preferred Return (preferredreturn.com): A 409a valuation service provider. </p>
<p>Gust Equity Management (equity.gust.com): A web application that primarily provides capitalization table management and other core services for early stage companies and entrepreneurs.</p>
<p>Fundacity (fundacity.com): A web application that primarily provides deal flow management and collaboration.</p>
<p>LeanMonitor (leanmonitor.com): A web application that primarily provides entrepreneur tools to test and validate ideas using the Lean Startup method.</p>
<p>Gust does not review or verify any User content, and does not and cannot guarantee that any User content is accurate or complete. In order to use the Gust Platform, you must use one of the supported Internet browsers. Additionally, you are required to register your User information with Gust. Gust does not provide internet access, and you are responsible for all fees associated with you internet connection. </p>
<h3><b>Registered Users</b></h3>
<p>Entrepreneurs: If you are an entrepreneur User, you may upload information about your business, including information you consider confidential and designate as confidential, and you may designate which Investors or Organizations may see that information. <mark>Notwithstanding the foregoing, in the event you begin an application to an accelerator application on the Gust Platform, you hereby expressly grant to Gust a license to share your, name, email address and application status (collectively “Basic Application Information”) with such accelerator at any point in your application process, regardless of designation unless you expressly opt out.  Basic Application Information will not be considered confidential information with respect to Gust’s disclosures to such accelerators unless you opt out. For the avoidance of doubt, the actual contents of your application will only be disclosed to accelerators upon submission of your final application.</mark> Please, be aware that Gust has no control over the actions of Investors or Organizations. Also, though we take all reasonable steps in accordance with industry standards to prevent it, we cannot guarantee that the Gust Platform will never suffer from a software bug or a hacker attack that will allow unauthorized viewing of confidential material, or that any Investor is actually accredited.</p>
<p>Investors: If you are classified by Gust as an Investor User, whether or not Accredited, you may have access to an entrepreneur’s confidential information either directly or through an Organization, and should use your discretion in how you handle that information. All Organizations will be overseen by an Administrator, who will determine membership and set rules and parameters as provided on the Gust Platform for that Organizations.</p>
<p>General Users: Certain portions of the Gust Platform will be visible to Users who have not registered as entrepreneurs, Organizations, or Accredited Investors. Those Users, nevertheless, are bound by these Terms of Service. Entrepreneurs should be aware that information they provide that is not designated as confidential will be visible to all Users. See User Content discussion in User Submissions Section below.</p>
<p>Gust shall have no obligation to participate or assist in any way in the event of any dispute between Users.</p>
<p>Notwithstanding the above or anything to the contrary set forth in the Terms of Service, Gust shall have the absolute and unlimited rights to reject any User, to terminate the account of any User, to delete any User Content, or to publish any User Content that is not confidential, including for the purposes of marketing Gust and/or the Gust Platform.</p>
<h3><b>License to Use</b></h3>
<p>Subject to the terms of these Terms of Service, which constitute the agreement between Gust and you, the User, Gust grants to you a non-exclusive, revocable, non-transferable license to use the Gust Platform. All right, title, and interest in and to the Gust Platform (excluding User Content) is and will remain the exclusive property of Gust and and/or its licensors. </p>
<h3><b>Accredited Investors</b></h3>
<p>Gust enables Users to self-accreditate, but Gust does not certify or verify the self-accreditation of any of its Users. All Users of the Gust Platform are advised that Gust does not take any steps to verify the information provided to us by the Accredited Investor, and does not and cannot guarantee that any investor actually qualifies as an Accredited Investor. Each User is solely responsible for conducting diligence on any Accredited Investor with whom that User interacts on the Gust Platform. Further, some of Gust’s Users may be located outside of the United States. Gust does not verify the compliance of any such Users with the applicable securities laws in their home jurisdiction and relies solely on their self-certification that they are in compliance with applicable laws. </p>
<h3><b>Securities</b></h3>
<p>Federal securities laws require that securities sold in the United States be registered with the Securities and Exchange Commission unless there is an exemption available under applicable law. “Securities” is a very broadly defined term under the United States securities law and will include most of the types of investment opportunities that are offered by early and growth stage ventures including, without limitation, promissory notes, convertible promissory notes, options, warrants, capital stock and other financial contracts that offer third parties a participation in profit-sharing or the potential growth of a business. The securities laws applicable to such private placements of securities are complicated and are currently in a state of flux due to certain changes adopted as part of the JumpStart Our Business Start-up Act of 2012 as to which rulemaking and implementation of the act by the Securities and Exchange Commission and the Financial Industry Regulatory Authority is ongoing. Such transactions are subject to both federal and state law and depending on the company involved and the location of the investors, may also be subject to foreign laws. To comply with certain provisions of applicable law necessary to qualify for exemptions from registration in the United States, there are limitations on the use of general solicitation or advertising. Gust is not responsible for determining and makes no representation as to whether any use of the Gust Platform constitutes general solicitation or advertising under applicable law. </p>
<p>By using the Gust Platform you understand and agree that you will be solely responsible for complying with all applicable law regarding any transaction in which you may engage, including without limitation the determination of whether any investor is an Accredited Investor and whether any investment complies with the terms of any United States law (or any law of any US state or foreign jurisdiction) or meets the criteria for any exemption from registration and/or disclosure available thereunder. </p>
<p>Gust does not recommend any investments, does not verify or review User documents or communications, and does not give business advice, financial advice, investment advice, tax advice or legal advice. Gust does not claim to be and is not registered as a broker-dealer and investment advisor. Nothing on this Gust Platform is intended to be or shall constitute or be construed as a sale or purchase or offer to sell or purchase or a recommendation of any securities. </p>
<h3><b>Purchases</b></h3>
<p>Some of Gust's services are provided free of charge, while others are provided for a fee. The fees for each service vary. </p>
<p>All product and service features, including availability and price, are subject to change at any time without notice. We reserve the right, with or without prior notice, to limit the availability of or to discontinue any product or service; to impose conditions on any promotion; to bar any user from making any purchase; and/or to refuse to provide any user with any product or service.</p>
<p>You authorize Gust to charge you for all products or services purchased by you through the Gust Platform, to the payment method you provide. "Charge" shall indicate either a charge or a debit, as applicable, against your payment method. If you request a purchase on a recurring basis, you agree that we may automatically charge the payment method you have provided at the regular intervals you have designated, unless and until you cancel according to our cancellation terms by selecting the cancellation option on your company profile page. You represent that you have the legal right to use any payment method that you submit to us. There will be no refunds or credits for prior months of service, partial months of service, upgrade/downgrade refunds, or refunds for months unused with an open account. In order to treat everyone equally, no exceptions will be made.</p>
<p>All orders placed through the Gust Platform are subject to our acceptance. Your receipt of an order confirmation does not signify our acceptance of your order. We reserve the right at any time after receipt of your order to accept or decline your order for any or no reason and without liability to you or anyone else. If your method of payment has already been charged for an order that we later cancel, we will issue you a refund. Prices are in U.S. dollars unless otherwise stated and are subject to change. We may require verification of information prior to the acceptance and/or fulfillment of any order.</p>
<h3><b>Our Proprietary Rights</b></h3>
<p>We and/or our licensors and suppliers own the information and materials made available through Gust, excluding User Content. Such information and materials are protected by copyright, trademark, patent and/or other proprietary rights and laws. Subject to your compliance with this Agreement, and solely for so long as you are permitted by us to access and use Gust, you may access, view and print a single copy of any content on Gust to which we provide you access hereunder, solely for your personal, internal business and non-commercial purposes, provided that you keep intact all copyright and other proprietary notices. Other than exercising rights you may have to documents provided to you by another user through the Services, or except as expressly authorized in advance by us in writing, you agree not to reproduce, modify, rent, lease, loan, sell, distribute, or create derivative works based on all or any part of Gust or any information or materials made available through Gust.</p>
<p>Our trade names, trademarks and service marks include, without limitation, Gust and any affiliated or associated logos. All trademarks and service marks on Gust not owned by us are the property of their respective owners. You may not use our trade names, trademarks or service marks in connection with any product or service that is not ours, in any manner that is likely to cause confusion. Nothing contained on Gust should be construed as granting any license or right to use any trade names, trademarks or service marks without the express prior written consent of the owner.</p>
<h3><b>Eligibility </b></h3>
<p>In order to access and use most of the Gust Platform, you must register for an account. If you are under the age of 18, please do not sign up for an account. Additionally, if you wish to use the Gust platform as an investor, you must be an Accredited Investor and so represent to Gust. Organizations may also register and will be overseen by the Organization Administrator.</p>
<h3><b>Limitations on Use </b></h3>
<p>In order to best serve our Users, and to comply with applicable laws, Gust has a limited number of rules which govern how you may behave while interacting with the Gust Platform and other Users. Please review the rules below carefully, since your violation of them may result in the termination of your access to the Gust Platform in Gust’s sole discretion at any time and without prior notice. </p>
<h3><b>Limitations on Service </b></h3>
<p>While it is our goal at Gust to provide you with a useful, stable and available service, we cannot guarantee that there will be no unforeseen difficulties, technical or otherwise, which may, in rare cases, result in service interruptions or loss of data. For this reason, the Gust Platform and all Content and services on it are provided strictly on an 'as is' basis. By accepting these Terms of Service, you agree that neither Gust nor any of its third party service providers will be held accountable for any delays in transmission of your data, data loss, service interruptions or retention of User settings. For a brief overview of our policies regarding the safeguarding of your data, please view our Privacy Policy at http://www.gust.com/privacy-policy </p>
<p>Gust reserves the right to change or discontinue, either temporarily or permanently, any part of the Gust Platform or any or all of its services at any time and without prior notice. You agree that neither Gust nor any of its third party service providers will be liable for any damages, including lost business opportunities, should such discontinuance occur. </p>
<h3><b>Data Accuracy </b></h3>
<p>We ask that any registration data you provide to Gust is true, current and complete. In the event any of this information changes, please update it on your personal profile page. For details on how you can access your stored data, please refer to Gust’s Privacy Policy. </p>
<h3><b>Passwords </b></h3>
<p>During your registration you will set your account access login and password. You are responsible for maintaining the confidentiality of this information and are responsible for any and all activities and postings that are made using your account. </p>
<p>Please notify Gust immediately if you suspect that an unauthorized person has accessed your account. Should you misplace or forget your password, please click on the forgot on the forgot password link. If you continue to have problems, please contact our technical support staff at support@gust.com.</p>
<h3><b>Compliance with Applicable Laws </b></h3>
<p>You agree to use the Gust Platform only as provided for in these Terms of Service. You also agree not to use the Gust Platform in any way that is in conflict with the law in your jurisdiction. Further, you may not use the Gust Platform for the transmission of any information that is obscene, libelous, harassing, abusive, threatening, invasive of a User's privacy, or in violation of any other individual's intellectual property rights. </p>
<h3><b>Email </b></h3>
<p>Please use the email features of the Gust Platform responsibly. You may not use the Gust Platform to send unsolicited commercial email ('spam') or unsolicited mass distribution of files. In order to enforce this provision, Gust may establish additional policies regarding the use of email features, including, but not limited to, maximum retention times of messages, maximum number of messages sent per day, or a maximum size of a message. </p>
<p>You agree not to use or launch any automated system, including without limitation, “robots,” “spiders,” “offline readers,” etc., that access the Gust Platform in a manner that sends more request messages to Gust’s servers in a given period of time than a human can reasonably produce in the same period by using a conventional on-line web browser. Notwithstanding the foregoing, Gust grants the operators of public search engines permission to use spiders to copy materials from the site for the sole purpose of creating publicly available searchable indices of the materials, but not caches or archives of such materials. Gust reserves the right to revoke these exceptions either generally or in specific cases. You agree not to collect or harvest any personally identifiable information, including account names, from the Gust Platform, nor to use the communication systems provided by the Gust Platform for any commercial solicitation purposes. </p>
<p>If you receive any email through the Gust Platform that you believe is not in compliance with the above provision, please notify us by forwarding the email, along with an explanatory note, to support@gust.com </p>
<h3><b>Privacy </b></h3>
<p>Gust is committed to protecting the privacy of its Users and has developed a detailed Privacy Policy that describes our practices and procedures regarding your data. The Privacy Policy is available at http://www.gust.com/privacy-policy, and is incorporated herein by reference. Please review the Privacy Policy before accepting this Agreement. </p>
<p>By registering with or using Gust, you consent to the collection and use of your personal information and the transfer of this information to the United States or other countries for processing and storage by Gust. </p>
<p>A User may elect to make certain confidential, personal or private information viewable through the Gust Platform. You may not disclose information obtained in this manner to any third parties without first obtaining permission from that User. You agree not to collect or aggregate User information accessible through the Gust Platform for commercial use or redistribution, including the targeted marketing of non-Gust services to individual Users. Gust reserves the right to immediately terminate, without notice, the account of any User found to have violated this rule in the sole and absolute discretion of Gust.</p>
<p>The Gust Platform provides entrepreneur Users the option to publish a subset of the data to non-registered Users in order to promote their presence on the Gust Platform, and to facilitate inviting the non-registered Users to join the Gust Platform to enable private collaboration. This includes basic information such as company name, location and one-line pitch, among other data. It also includes their company overview, pitch video and profiles for members of their team. </p>
<p>The Gust Platform also provides administrators of Organizations the option to publish a subset of the data to non-registered Users in order to promote their presence on the Gust Platform, and to facilitate inviting the non-registered Users to join the Gust Platform to enable private collaboration. This includes a profile to market themselves to entrepreneurs, which includes basic information such as the Organization’s name, location, investment preferences and portfolio companies. </p>
<p>All of the data for each respective User is exclusively entered and maintained by the user. Each User may (but does not have to) opt-in to publishing this information and always has the power to remove it from the public domain by un-publishing it. All other data entered on Gust is shared with other Users on the Gust Platform exclusively by the User's affirmative action; this data is, and always will, remain privately available only to those Users. Gust will never use this information in a personally identifiable way.</p>
<h3><b>Prohibited Activities</b></h3>
<p>In general, as a condition to your continued use of the Gust Platform, you agree that you will not use the Gust Platform for any purpose that is unlawful or prohibited by these Terms of Service. In the access or use of the Gust Platform, you shall comply with these Terms of Service and the special warnings or instructions for access or use posted on the Gust Platform. You shall act always in accordance with the law, custom and in good faith. You may not make any change or alteration to the Gust Platform or any Gust Content or services that may appear on the Gust Platform and you may not impair in any way the integrity or operation of the Gust Platform. Without limiting the generality of any other provision of these Terms of Service, if you default negligently or willfully in any of the obligations set forth in these Terms of Service, you shall be liable for all the losses and damages that this may cause to Gust, our affiliates, partners or licensors.</p>
<p>By way of example, and not limitation, you agree not to:</p>
<p>Post, transmit, or otherwise make available through or in connection with your use of the Gust Platform:</p>
<p>Any information or materials that are or may be, or the posting, transmission or use of which is or may be: (a) threatening, harassing, degrading, hateful or intimidating; (b) defamatory or libelous; (c) fraudulent or tortious; (d) obscene, indecent, pornographic or otherwise objectionable; or (e) protected by copyright, trademark, trade secret, right of publicity or privacy or any other proprietary right of any third party.</p>
<p>Any material that would give rise to criminal or civil liability; that encourages conduct that constitutes a criminal offense; or that encourages or provides instructional information about illegal activities or activities such as “hacking,” “cracking,” or “phreaking.”</p>
<p>Any virus, worm, Trojan horse, Easter egg, time bomb, spyware, or other computer code, file, or program that is harmful or invasive or that may or is intended to damage, hijack, disable, interfere with, or disrupt the operation of, or monitor the use of, any hardware, software or equipment.</p>
<p>Any unsolicited or unauthorized advertisements, promotional material, “junk mail,” “spam,” “chain letter,” “pyramid scheme” or investment opportunity, or any other form of solicitation that is not expressly approved in writing by Gust in advance.</p>
<p>Any personally identifiable information of another individual, without the prior consent of such individual.</p>
<p>Any material, non-public information about a company, without the proper authorization to do so.</p>
<p>Use the Gust Platform for any fraudulent or unlawful purpose.</p>
<p>Use the Gust if you are a competitor of the Company, or for reasons that are in competition with the Company.</p>
<p>Use the Gust Platform to defame, abuse, harass, stalk, threaten or otherwise violate the legal rights of others, including without limitation others’ privacy rights or rights of publicity, or to harvest or collect information about Users of the Gust Platform.</p>
<p>Impersonate any person or entity, including without limitation any representative of Gust or any other company; falsely state or otherwise misrepresent your affiliation with any person or entity in connection with the Gust Platform; or express or imply that Gust endorses any statement you make.</p>
<p>Interfere with or disrupt the operation of the Gust Platform or the servers or networks used to make the Gust Platform available; or violate any requirements, procedures, policies or regulations of such networks.</p>
<p>Restrict or inhibit any other person from using the Gust Platform (including without limitation by hacking or defacing any portion of the Gust Platform).</p>
<p>Reproduce, duplicate, copy, sell, resell, link to or otherwise exploit for any commercial purposes, any portion of, use of, or access to, the Gust Platform.</p>
<p>Modify, adapt, translate, reverse engineer, decompile or disassemble any portion of the Gust Platform.</p>
<p>Remove any copyright, trademark or other proprietary rights notice from the Gust Platform or materials originating from the Gust Platform.</p>
<p>Frame or mirror any part of the Gust Platform.</p>
<p>Create a database by downloading and storing Gust Platform Content.</p>
<p>Use any robot, spider, site search/retrieval application or other manual or automatic device to retrieve, index, “scrape,” “data mine” or in any way Gust Platform Content or reproduce or circumvent the navigational structure or presentation of the Gust Platform without Gust’s express prior written consent.</p>
<h3><b>User Submissions</b></h3>
<p>We do not accept unsolicited suggestions and/or ideas. All inquiries, feedback, suggestions, ideas or other information any User provides to Gust concerning the Gust Platform (collectively, “Submissions”) will be treated as non-proprietary and non-confidential. By transmitting or posting any Submission, the User hereby grants Gust full ownership of the Submission as if Gust had created, developed and posted the Submission for its own purposes. Please note this is different from User Content, which is addressed below. Gust reserves the right to copy, use, reproduce, modify, adapt, translate, publish, license, distribute, sell or assign the Submission in any way as it sees fit, including but not limited to copying in whole or in part, creating derivative works from, distributing and displaying any Submission in any form, media, or technology, whether now known or hereafter developed, alone or as part of other works, or using the Submission within or in connection with Gust’s products or services. User also acknowledges that User Submissions will not be returned and Gust may use Submissions, and any ideas, concepts or know how contained therein, without payment of money or any other form of consideration, for any purpose including, without limitation, developing, manufacturing, distributing and marketing products. For clarification, deal documents and emails or other communications between Users are not considered Submissions; Gust claims no right, title or interest in such documents or communications.</p>
<p>If a User makes a Submission, the User represents and warrants that the User owns or otherwise control the rights to the Submission. User further represents and warrants that such Submission does not constitute or contain software viruses, commercial solicitation, chain letters, mass mailings, or any form of “spam.” Users may not use a false email address, impersonate any person or entity, or otherwise mislead Gust as to the origin of any Submission. The User agrees to indemnify Gust for all claims arising from or in connection with any claims to any rights in any Submission or any damages arising from any Submission.<br />
<br />
<h3>User Content</b></h3>
<p>The Gust Platform permits the submission of content or communications submitted by Users (“User Content”) and the hosting, sharing, and/or publishing of such User Content. </p>
<p>Gust does not and will not claim any ownership over or rights to User Content other than a license to display it on the Gust Platform as directed by the User, but User understands that whether or not such User Content is published, though Gust will seek to maintain the confidentiality of any data designated as confidential by a User, Gust does not guarantee any confidentiality with respect to any User Content.</p>
<p>User shall be solely responsible for User’s own User Content and the consequences of posting or publishing them. In connection with User Content, User affirms, represents, and/or warrants that: (i) User owns or has the necessary licenses, rights, consents, and permissions to use and authorize Gust to use all patent, trademark, trade secret, copyright or other proprietary rights in and to any and all User Content to enable inclusion and use of the User Content in the manner contemplated by the Gust Platform and these Terms of Service; and (ii) User has the written consent, release, and/or permission of each and every identifiable individual person in the User Content to use the name or likeness of each and every such identifiable individual person to enable inclusion and use of the User Content in the manner contemplated by the Gust Platform and these Terms of Service.</p>
<p>By submitting the User Content to the Gust Platform, User hereby grants Gust a worldwide, non-exclusive, royalty-free, sublicenseable and transferable license to use, reproduce, distribute, prepare derivative works of, display, and perform the User Content in connection with the Gust Platform and Gust’s (and its successor’s) business, including without limitation for promoting and redistributing part or all of the Gust Platform (and derivative works thereof) in any media formats and through any media channels. In the event it does so, Gust will seek to maintain the confidentiality of User Content consistent with the User’s designation, but once again cannot guarantee any such confidentiality. User also grants each User of the Gust Platform a non-exclusive license to access the User Content of that User through the Gust Platform, and to use, reproduce, distribute, prepare derivative works of, display and perform such User Content as permitted through the functionality of the Gust Platform and under these Terms of Service. The foregoing license granted by User terminates once User or Gust removes or deletes any User Content from the Gust Platform.</p>
<p>User agrees that User will not: (i) submit material that is copyrighted, protected by trade secret or otherwise subject to third party proprietary rights, including privacy and publicity rights, unless User is the owner of such rights or have permission from their rightful owner to post the material and to grant Gust all of the license rights granted herein; (ii) publish falsehoods or misrepresentations that could damage Gust or any third party; (iii) submit material that is unlawful, obscene, defamatory, libelous, threatening, pornographic, harassing, hateful, racially or ethnically offensive, or encourages conduct that would be considered a criminal offense, give rise to civil liability, violate any law, or is otherwise inappropriate; (iv) post advertisements or solicitations of business; (v) impersonate another person.</p>
<p>Gust does not endorse any User Content or any opinion, recommendation, or advice expressed therein, and expressly disclaims any and all liability in connection with User Content. Gust does not knowingly permit infringement of intellectual property rights on its Gust Platform, and will remove all User Content if properly notified that such User Content infringes on another’s intellectual property rights. Gust reserves the right to remove User Content without prior notice. Gust will also terminate a User’s access to its Gust Platform, if a User is determined to be a repeat infringer. Gust also reserves the right to decide whether User Content is appropriate and complies with these Terms of Service for violations other than copyright infringement and violations of intellectual property law, such as, but not limited to, pornography, obscene or defamatory material, or excessive length. Gust may remove such User Content and/or terminate a User’s access for uploading such material in violation of these Terms of Service at any time, without prior notice and at its sole discretion.</p>
<p>If you are a copyright owner or an agent thereof and believe that any User Content or other Content infringes upon your copyrights, you may submit a notification pursuant to the Digital Millennium Copyright Act (“DMCA”) by providing our Copyright Agent with the following information in writing:</p>
<p>A physical or electronic signature of a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed;</p>
<p>Identification of the copyrighted work claimed to have been infringed, or, if multiple copyrighted works at a single online site are covered by a single notification, a representative list of such works at that site;</p>
<p>Identification of the material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled and information reasonably sufficient to permit the service provider to locate the material;</p>
<p>Information reasonably sufficient to permit the service provider to contact you, such as an address, telephone number, and, if available, an electronic mail;</p>
<p>A statement that you have a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law; and</p>
<p>A statement that the information in the notification is accurate, and under penalty of perjury, that you are authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.</p>
<p>The Company’s designated Copyright Agent to receive notifications of claimed infringement is: Randy M. Friedberg, Esq., White and Williams LLP, One Penn Plaza, 41st Floor, New York, New York, 10119; email: friedbergr@whiteandwilliams.com. Only DMCA notices should go to the Copyright Agent. Notices and counter-notices must meet the then-current statutory requirements imposed by the DMCA. Gust suggests that you consult your legal advisor before filing a notice. Please be aware that there are penalties for false claims under the DMCA. Any other feedback, comments, requests for technical support, and other communications should be directed to Company customer service through support@gust.com. You acknowledge that if you fail to comply with all of the requirements of this Section, your DMCA notice may not be valid.</p>
<p>You understand that when using the Gust Platform, you may be exposed to User Content from a variety of sources, and that Gust is not responsible for the accuracy, usefulness, safety, or intellectual property rights of or relating to such User Content . You further understand and acknowledge that you may be exposed to User Content that are inaccurate, offensive, indecent, or objectionable, and you agree to waive, and hereby do waive, any legal or equitable rights or remedies you have or may have against Gust with respect thereto, and agree to indemnify and hold Gust, its owners/operators, affiliates, and/or licensors, harmless to the fullest extent allowed by law regarding all matters related to your use of the Gust Platform.</p>
<h3><b>Intellectual Property</b></h3>
<p>All information and Content available on the Gust Platform and its “look and feel”, except all User Content (as defined herein), including but not limited to trademarks, logos, service marks, copyrighted works, text, graphics, logos, button icons, images, audio/video clips, data compilations and software, and the compilation and organization thereof is the property of Gust, its affiliates, partners or licensors, or is used with consent of the owner, and is protected by United States and international laws, including laws governing copyrights and trademarks. The reproduction and use of any of these by you is prohibited unless specific permission is provided on the Gust Platform or otherwise. Any unauthorized use may violate copyright laws, trademark laws, privacy and publicity laws, and/or communications regulations and statutes of the United States and foreign laws and international conventions.</p>
<p>The trademarks, service marks, logos, and other indicia, including of Gust (collectively the “Trademarks”) which appear on the Gust Platform are registered and/or unregistered trademarks of Gust and others. Nothing contained on the Gust Platform should be construed as granting, by implication or otherwise, any right, license or title to any of the Trademarks without the advance written permission of Gust or such third party as may be appropriate. All rights are expressly reserved and retained by Gust. Your misuse of any of the Trademarks displayed on the Gust Platform, or any other Content on the Gust Platform, except as provided in these Terms Of Service, is strictly prohibited. You are also advised that Gust considers its intellectual property to be among its most valuable assets, and will aggressively enforce its intellectual property rights to the fullest extent of the law.</p>
<p>Both the Gust Platform and the Content of the Gust Platform are provided “AS IS” for Users information and personal use only and may not be used, copied, reproduced, distributed, transmitted, broadcast, displayed, sold, licensed, or otherwise exploited for any other purposes whatsoever without the prior written consent of the respective owners. Gust reserves all rights not expressly granted in and to the Gust Platform and the Content. User agrees to not engage in the use, copying, or distribution of any of the Content other than expressly permitted herein, including any use, copying, or distribution of User submissions of third parties obtained through the Gust Platform for any commercial purposes. If User downloads or prints Content for personal use, User must retain all copyright and other proprietary notices contained therein. User agrees not to circumvent, disable or otherwise interfere with security related features of the Gust Platform or features that prevent or restrict use or copying of any Content or enforce limitations on use of the Gust Platform or the Content thereon. Gust does not make any representations or warranties, whether express or implied, regarding or relating to the Gust Platform or any associated hardware or software, including the Content or operations of either.</p>
<h3><b>Disclaimers </b></h3>
<p>NONE OF GUST, ITS AFFILIATES, THEIR RESPECTIVE MEMBERS, OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, SUPPLIERS, OR LICENSORS (COLLECTIVELY, THE ‘<b>GUST PARTIES’ </b>) MAKES ANY WARRANTIES OR REPRESENTATIONS ABOUT THE GUST PLATFORM OR ITS CONTENTS, INCLUDING BUT NOT LIMITED TO THEIR ACCURACY, RELIABILITY, COMPLETENESS, OR TIMELINESS, OR RELIABILITY. NONE OF THE GUST PARTIES SHALL BE SUBJECT TO LIABILITY FOR TRUTH, ACCURACY, OR COMPLETENESS OF ANY INFORMATION MADE AVAILABLE ON OR THROUGH THE GUST PLATFORM OR FOR ERRORS, MISTAKES OR OMISSIONS THEREIN OR FOR ANY DELAYS OR INTERRUPTIONS OF THE DATA OR INFORMATION STREAM FROM WHATEVER CAUSE. YOU AGREE THAT YOU USE THE GUST PLATFORM A SOLELY AT YOUR OWN RISK. </p>
<p>GUST PROVIDES THIS GUST PLATFORM AS A RESOURCE FOR USERS INVOLVED WITH INVESTING IN EARLY STAGE TECHNOLOGY AND EMERGING GROWTH COMPANIES BUT GUST DOES NOT GIVE BUSINESS ADVICE, INVESTMENT ADVICE, TAX ADVICE OR LEGAL ADVICE TO ANYONE USING THE GUST PLATFORM. GUST DOES NOT CLAIM TO BE AND IS NOT A BROKER, DEALER OR INVESTMENT ADVISOR AND NOTHING HEREIN SHALL CONSTITUTE A SALE OR OFFER TO BUY OR SELL OR RECOMMEND ANY SECURITIES. GUST DOES NOT MAKE INVESTMENTS. EACH USER OF THE GUST PLATFORM MAKE HIS OR HER OWN INVESTMENT DECISIONS BASED UPON HIS OR HER PERSONAL DUE DILIGENCE INVESTIGATION AND OTHER PERSONAL INVESTMENT CRITERIA. GUST IS NOT RESPONSIBLE FOR AND SHALL HAVE NO LIABILITY WITH RESPECT TO THE ACTIONS OR OMISSIONS OF ANYONE USING THE GUST PLATFORM. AS A CONDITION TO YOUR USE OF THE GUST PLATFORM, YOU HEREBY WAIVE AND RELEASE ANY AND ALL CLAIMS, CAUSES OF ACTION OR OTHER RIGHTS THAT YOU MIGHT HAVE AGAINST ANY OF THE GUST PARTIES ARISING OUT OF OR RELATING TO THE SUBMISSION AND REVIEW OF ANY MATERIALS MADE AVAILABLE ON OR THROUGH THE GUST PLATFORM. </p>
<p>GUST DOES NOT AGREE TO ANY OBLIGATIONS OF CONFIDENTIALITY, NONDISCLOSURE OR NONUSE, EXCEPT AS EXPLICITLY PROVIDED FOR IN OUR PRIVACY POLICY. </p>
<p>IN NO EVENT SHALL ANY GUST PARTY BE LIABLE FOR ANY DAMAGES WHATSOEVER (INCLUDING, WITHOUT LIMITATION, INCIDENTAL AND CONSEQUENTIAL DAMAGES, LOST PROFITS, OR DAMAGES RESULTING FROM LOST DATA OR BUSINESS INTERRUPTION) RESULTING FROM EITHER A PERSON OR ENTITY'S USE OR INABILITY TO USE THE GUST PLATFORM, OR THE SUBMISSION OF ANY MATERIALS VIA THE GUST PLATFORM, WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), OR ANY OTHER LEGAL THEORY, EVEN IF A GUST PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. </p>
<p>Some states do not allow exclusion of implied warranties or limitation of liability for incidental or consequential damages, so the above limitations or exclusions may not apply to you. IN SUCH STATES, THE LIABILITY OF THE GUST PARTIES SHALL BE LIMITED TO THE GREATEST EXTENT PERMITTED BY LAW. </p>
<h3><b>Indemnification </b></h3>
<p>At Gust's request, User agrees to defend, indemnify and hold harmless Gust, its shareholders, partners, affiliates, directors, officers, subsidiaries, employees, agents, licensees, distributors and content providers from all damages, liabilities, claims and expenses, including without limitation attorneys' fees and costs, arising from or related, directly or indirectly, to any misuse of the Gust Platform or breach of this Agreement by User. </p>
<h3><b>Termination </b></h3>
<p>Gust reserves the right to suspend or terminate these Terms of Service and/or any User’s access to the Gust Platform at any time and without notice in its sole discretion. </p>
<h3><b>Entire Agreement/Severability </b></h3>
<p>These Terms of Service, together with the Privacy Notice and any other legal notices published by Gust on the Gust Platform, shall constitute the entire agreement between you and Gust concerning the Gust Platform. If any provision of these Terms of Service is deemed invalid by a court of competent jurisdiction, the invalidity of such provision shall not affect the validity of the remaining provisions of these Terms of Service, which shall remain in full force and effect. No waiver of any term of this these Terms of Service shall be deemed a further or continuing waiver of such term or any other term, and Gust’s failure to assert any right or provision under these Terms of Service shall not constitute a waiver of such right or provision. </p>
<h3><b>Arbitration </b></h3>
<p>You agree that: (i) the Gust Platform shall be deemed solely based in New York, New York; and (ii) the Gust Platform shall be deemed a passive website that does not give rise to personal jurisdiction over Gust, either specific or general, in jurisdictions other than New York. These Terms of Service shall be governed by the internal substantive laws of the State of New York, without respect to its conflict of laws principles. All disputes arising out of or relating to this Agreement shall be finally resolved by arbitration conducted in New York, NY under the rules of commercial arbitration of the American Arbitration Association. Both parties shall bear equally the cost of arbitration (exclusive of legal fees and expenses). All decisions of the arbitrator(s) shall be final and binding on both parties and enforceable in any court of competent jurisdiction. </p>
<h3><b>Modifications to the Terms of Service </b></h3>
<p>Gust may change these Terms of Service at any time and in its sole discretion. The modified Terms of Service will be effective immediately upon posting and you agree to the new posted Terms of Service by continuing your use the Gust Platform. Gust will provide at least 10-days' notice before any material changes take effect. If you do not agree with the modified Terms of Service, your only remedy is to discontinue using the Gust Platform. Notwithstanding the foregoing, any changes to this Agreement shall not apply to any dispute between you and us arising prior to the date of such posting or other notification. We may, at any time, temporarily or permanently modify or discontinue all or part of Gust, with or without notice and/or offer opportunities to some or all users of Gust. You agree that the Gust Platform shall not be liable to you or to any third party for any modification, suspension or discontinuance of Gust, in whole or in part, or of any Service, content, feature or product offered through Gust. You agree that we may, at any time, charge fees in connection with the use of all or part of Gust and/or for certain features of the Services and that you will be responsible for all such charges (including any applicable tax). You will be notified in advance of any such charges.</p>
<p>USER ACKNOWLEDGES THAT USER HAS READ THIS AGREEMENT, UNDERSTANDS IT, AND AGREES TO BE BOUND BY ITS TERMS AND CONDITIONS. USER FURTHER AGREES THAT IT IS THE COMPLETE AND EXCLUSIVE STATEMENT OF THE AGREEMENT BETWEEN USER AND GUST WHICH SUPERSEDES ANY PROPOSAL OR PRIOR AGREEMENT, WRITTEN OR ORAL, AND ANY OTHER COMMUNICATION BETWEEN USER AND GUST RELATING TO THE SUBJECT MATTER OF THIS TERMS OF SERVICE. </p>
<p>Should you have any questions concerning these Terms Of Service, please email Us </a>.</p>


</div>

</div>


</div>



<?php
include('includes/footer.php');
include('includes/scripts.php');
?>